<?php

declare(strict_types=1);

namespace WeArePlanet\PluginCore\Refund;

enum Type: string
{
    case MERCHANT_INITIATED_ONLINE = 'MERCHANT_INITIATED_ONLINE';
    case MERCHANT_INITIATED_OFFLINE = 'MERCHANT_INITIATED_OFFLINE';
    case CUSTOMER_INITIATED_AUTOMATIC = 'CUSTOMER_INITIATED_AUTOMATIC';
    case CUSTOMER_INITIATED_MANUAL = 'CUSTOMER_INITIATED_MANUAL';
}
